/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-14 09:24:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.vendor;

public final class vendor_002dindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/vendor-header.jsp", Long.valueOf(1715678693861L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("Model.vendor");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Rentaly - Multipurpose Vehicle Car Rental Website\r\n");
      out.write("	Template</title>\r\n");
      out.write("<link rel=\"icon\" href=\"images/icon.png\" type=\"image/gif\" sizes=\"16x16\">\r\n");
      out.write("<meta content=\"text/html;charset=utf-8\" http-equiv=\"Content-Type\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta\r\n");
      out.write("	content=\"Rentaly - Multipurpose Vehicle Car Rental Website Template\"\r\n");
      out.write("	name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"author\">\r\n");
      out.write("<!-- CSS Files\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	id=\"bootstrap\">\r\n");
      out.write("<link href=\"css/mdb.min.css\" rel=\"stylesheet\" type=\"text/css\" id=\"mdb\">\r\n");
      out.write("<link href=\"css/plugins.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/coloring.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- color scheme -->\r\n");
      out.write("<link id=\"colors\" href=\"css/colors/scheme-01.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- page preloader begin -->\r\n");
      out.write("		<div id=\"de-preloader\"></div>\r\n");
      out.write("		<!-- page preloader close -->\r\n");
      out.write("\r\n");
      out.write("		<!-- header begin -->\r\n");
      out.write("		<header class=\"transparent scroll-light has-topbar\">\r\n");
      out.write("			<div id=\"topbar\" class=\"topbar-dark text-light\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"topbar-left xs-hide\">\r\n");
      out.write("						<div class=\"topbar-widget\">\r\n");
      out.write("							<div class=\"topbar-widget\">\r\n");
      out.write("								<a href=\"#\"><i class=\"fa fa-phone\"></i>+208 333 9296</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"topbar-widget\">\r\n");
      out.write("								<a href=\"#\"><i class=\"fa fa-envelope\"></i>contact@rentaly.com</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"topbar-widget\">\r\n");
      out.write("								<a href=\"#\"><i class=\"fa fa-clock-o\"></i>Mon - Fri 08.00 -\r\n");
      out.write("									18.00</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					vendor v = null;

					if (session.getAttribute("data") != null) {

						v = (vendor) session.getAttribute("data");
					} else {
						response.sendRedirect("vendor-login.jsp");
					}
					
      out.write("\r\n");
      out.write("					<div class=\"topbar-right\">\r\n");
      out.write("						<div class=\"social-icons\">\r\n");
      out.write("							<a href=\"#\"><i class=\"fa fa-facebook fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-twitter fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-youtube fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-pinterest fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-instagram fa-lg\"></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-12\">\r\n");
      out.write("						<div class=\"de-flex sm-pt10\">\r\n");
      out.write("							<div class=\"de-flex-col\">\r\n");
      out.write("								<div class=\"de-flex-col\">\r\n");
      out.write("									<!-- logo begin -->\r\n");
      out.write("									<div id=\"logo\">\r\n");
      out.write("										<a href=\"index.html\"> <img class=\"logo-1\"\r\n");
      out.write("											src=\"images/logo-light.png\" alt=\"\"> <img class=\"logo-2\"\r\n");
      out.write("											src=\"images/logo.png\" alt=\"\">\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- logo close -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"de-flex-col header-col-mid\">\r\n");
      out.write("								<ul id=\"mainmenu\">\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"index.html\">Home</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index.html\">Homepage\r\n");
      out.write("													1</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index-2.html\">Homepage\r\n");
      out.write("													2</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index-3.html\">Homepage\r\n");
      out.write("													3</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index-4.html\">Homepage\r\n");
      out.write("													4</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index-5.html\">Homepage\r\n");
      out.write("													5</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index-6.html\">Homepage\r\n");
      out.write("													6</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"index-7.html\">New:\r\n");
      out.write("													Homepage 7</a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"cars.html\">Cars</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"cars.html\">Cars List\r\n");
      out.write("													1</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"cars-list.html\">Cars\r\n");
      out.write("													List 2</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"car-single.html\">Cars\r\n");
      out.write("													Single</a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"booking.html\">Booking</a></li>\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"account-dashboard.html\">My\r\n");
      out.write("											Account</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"account-dashboard.html\">Dashboard</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"account-profile.html\">My\r\n");
      out.write("													Profile</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"account-booking.html\">My\r\n");
      out.write("													Orders</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"account-favorite.html\">My\r\n");
      out.write("													Favorite Cars</a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"#\">Pages</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"about.html\">About Us</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"login.html\">Login</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"register.html\">Register</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"404.html\">Page 404</a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"#\">News</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a class=\"menu-item\"\r\n");
      out.write("												href=\"news-standart-right-sidebar.html\">News Standard</a>\r\n");
      out.write("												<ul>\r\n");
      out.write("													<li><a class=\"menu-item\"\r\n");
      out.write("														href=\"news-standart-right-sidebar.html\">Right Sidebar</a></li>\r\n");
      out.write("													<li><a class=\"menu-item\"\r\n");
      out.write("														href=\"news-standart-left-sidebar.html\">Left Sidebar</a></li>\r\n");
      out.write("													<li><a class=\"menu-item\"\r\n");
      out.write("														href=\"news-standart-no-sidebar.html\">No Sidebar</a></li>\r\n");
      out.write("												</ul></li>\r\n");
      out.write("											<li><a class=\"menu-item\"\r\n");
      out.write("												href=\"news-grid-right-sidebar.html\">News Grid</a>\r\n");
      out.write("												<ul>\r\n");
      out.write("													<li><a class=\"menu-item\"\r\n");
      out.write("														href=\"news-grid-right-sidebar.html\">Right Sidebar</a></li>\r\n");
      out.write("													<li><a class=\"menu-item\"\r\n");
      out.write("														href=\"news-grid-left-sidebar.html\">Left Sidebar</a></li>\r\n");
      out.write("													<li><a class=\"menu-item\"\r\n");
      out.write("														href=\"news-grid-no-sidebar.html\">No Sidebar</a></li>\r\n");
      out.write("												</ul></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li><a class=\"menu-item\" href=\"#\">Elements</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"preloader.html\">Preloader</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"icon-boxes.html\">Icon\r\n");
      out.write("													Boxes</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"badge.html\">Badge</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"counters.html\">Counters</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"gallery-popup.html\">Gallery\r\n");
      out.write("													Popup</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"icons-elegant.html\">Icons\r\n");
      out.write("													Elegant</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"icons-etline.html\">Icons\r\n");
      out.write("													Etline</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"icons-font-awesome.html\">Icons\r\n");
      out.write("													Font Awesome</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"map.html\">Map</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"modal.html\">Modal</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"popover.html\">Popover</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"tabs.html\">Tabs</a></li>\r\n");
      out.write("											<li><a class=\"menu-item\" href=\"tooltips.html\">Tooltips</a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"de-flex-col\">\r\n");
      out.write("								<div class=\"menu_side_area\">\r\n");
      out.write("									<div class=\"de-login-menu\">\r\n");
      out.write("\r\n");
      out.write("										<span id=\"de-click-menu-profile\" class=\"de-menu-profile\">\r\n");
      out.write("											<img src=\"images/profile/1.jpg\"\r\n");
      out.write("											class=\"img-fluid\" alt=\"\">\r\n");
      out.write("										</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div id=\"de-submenu-profile\" class=\"de-submenu\">\r\n");
      out.write("											<div class=\"d-name\">\r\n");
      out.write("												<h4>\r\n");
      out.write("													");
      out.print(v.getName());
      out.write("\r\n");
      out.write("												</h4>\r\n");
      out.write("												<span class=\"text-gray\">");
      out.print(v.getEmail());
      out.write("</span>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"d-line\"></div>\r\n");
      out.write("\r\n");
      out.write("											<ul class=\"menu-col\">\r\n");
      out.write("												<li><a href=\"account-dashboard.html\"><i\r\n");
      out.write("														class=\"fa fa-home\"></i>Dashboard</a></li>\r\n");
      out.write("												<li><a href=\"vendor-profile.jsp\"><i\r\n");
      out.write("														class=\"fa fa-user\"></i>My Profile</a></li>\r\n");
      out.write("												<li><a href=\"v-cp.jsp\"><i class=\"fa fa-sign-out\"></i>Change\r\n");
      out.write("														Password</a></li>\r\n");
      out.write("												<li><a href=\"account-booking.html\"><i\r\n");
      out.write("														class=\"fa fa-calendar\"></i>My Orders</a></li>\r\n");
      out.write("												<li><a href=\"account-favorite.html\"><i\r\n");
      out.write("														class=\"fa fa-car\"></i>My Favorite Cars</a></li>\r\n");
      out.write("												<li><a href=\"vendor-Logout.jsp\"><i\r\n");
      out.write("														class=\"fa fa-sign-out\"></i>Sign Out</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("										<span id=\"menu-btn\"></span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!-- header close -->\r\n");
      out.write("		<!-- content begin -->\r\n");
      out.write("		<div class=\"no-bottom no-top zebra\" id=\"content\">\r\n");
      out.write("			<div id=\"top\"></div>\r\n");
      out.write("\r\n");
      out.write("			<!-- section begin -->\r\n");
      out.write("			<section id=\"subheader\" class=\"jarallax text-light\">\r\n");
      out.write("				<img src=\"images/background/14.jpg\" class=\"jarallax-img\" alt=\"\">\r\n");
      out.write("				<div class=\"center-y relative text-center\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-12 text-center\"></div>\r\n");
      out.write("							<div class=\"clearfix\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			<!-- section close -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- content close -->\r\n");
      out.write("\r\n");
      out.write("		<a href=\"#\" id=\"back-to-top\"></a>\r\n");
      out.write("\r\n");
      out.write("		<!-- footer begin -->\r\n");
      out.write("		<!-- footer close -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Javascript Files\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("	<script src=\"js/plugins.js\"></script>\r\n");
      out.write("	<script src=\"js/designesia.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>hsdgyucbdsv</h2>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
