/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-14 06:37:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vendor_002dregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/index-header.jsp", Long.valueOf(1715320898872L));
    _jspx_dependants.put("/index-footer.jsp", Long.valueOf(1715316628831L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Rentaly - Multipurpose Vehicle Car Rental Website\r\n");
      out.write("	Template</title>\r\n");
      out.write("<link rel=\"icon\" href=\"images/icon.png\" type=\"image/gif\" sizes=\"16x16\">\r\n");
      out.write("<meta content=\"text/html;charset=utf-8\" http-equiv=\"Content-Type\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta\r\n");
      out.write("	content=\"Rentaly - Multipurpose Vehicle Car Rental Website Template\"\r\n");
      out.write("	name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"author\">\r\n");
      out.write("<!-- CSS Files\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	id=\"bootstrap\">\r\n");
      out.write("<link href=\"css/mdb.min.css\" rel=\"stylesheet\" type=\"text/css\" id=\"mdb\">\r\n");
      out.write("<link href=\"css/plugins.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/coloring.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!-- color scheme -->\r\n");
      out.write("<link id=\"colors\" href=\"css/colors/scheme-01.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"transparent scroll-light has-topbar\">\r\n");
      out.write("		<div id=\"topbar\" class=\"topbar-dark text-light\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"topbar-left xs-hide\">\r\n");
      out.write("					<div class=\"topbar-widget\">\r\n");
      out.write("						<div class=\"topbar-widget\">\r\n");
      out.write("							<a href=\"#\"><i class=\"fa fa-phone\"></i>+208 333 9296</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"topbar-widget\">\r\n");
      out.write("							<a href=\"#\"><i class=\"fa fa-envelope\"></i>contact@rentaly.com</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"topbar-widget\">\r\n");
      out.write("							<a href=\"#\"><i class=\"fa fa-clock-o\"></i>Mon - Fri 08.00 -\r\n");
      out.write("								18.00</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"topbar-right\">\r\n");
      out.write("					<div class=\"social-icons\">\r\n");
      out.write("						<a href=\"#\"><i class=\"fa fa-facebook fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-twitter fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-youtube fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-pinterest fa-lg\"></i></a> <a href=\"#\"><i\r\n");
      out.write("							class=\"fa fa-instagram fa-lg\"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-12\">\r\n");
      out.write("					<div class=\"de-flex sm-pt10\">\r\n");
      out.write("						<div class=\"de-flex-col\">\r\n");
      out.write("							<div class=\"de-flex-col\">\r\n");
      out.write("								<!-- logo begin -->\r\n");
      out.write("								<div id=\"logo\">\r\n");
      out.write("									<a href=\"index.html\"> <img class=\"logo-1\"\r\n");
      out.write("										src=\"images/logo-light.png\" alt=\"\"> <img class=\"logo-2\"\r\n");
      out.write("										src=\"images/logo.png\" alt=\"\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- logo close -->\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"de-flex-col header-col-mid\">\r\n");
      out.write("							<ul id=\"mainmenu\">\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"index.html\">Home</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index.html\">Homepage 1</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index-2.html\">Homepage\r\n");
      out.write("												2</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index-3.html\">Homepage\r\n");
      out.write("												3</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index-4.html\">Homepage\r\n");
      out.write("												4</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index-5.html\">Homepage\r\n");
      out.write("												5</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index-6.html\">Homepage\r\n");
      out.write("												6</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"index-7.html\">New:\r\n");
      out.write("												Homepage 7</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"cars.html\">Cars</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"cars.html\">Cars List 1</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"cars-list.html\">Cars\r\n");
      out.write("												List 2</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"car-single.html\">Cars\r\n");
      out.write("												Single</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"booking.html\">Booking</a></li>\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"account-dashboard.html\">My\r\n");
      out.write("										Account</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"account-dashboard.html\">Dashboard</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"account-profile.html\">My\r\n");
      out.write("												Profile</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"account-booking.html\">My\r\n");
      out.write("												Orders</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"account-favorite.html\">My\r\n");
      out.write("												Favorite Cars</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"#\">Pages</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"about.html\">About Us</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"customer-login.jsp\">Login</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"customer-register.html\">Register</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"404.html\">Page 404</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"#\">News</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"menu-item\"\r\n");
      out.write("											href=\"news-standart-right-sidebar.html\">News Standard</a>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a class=\"menu-item\"\r\n");
      out.write("													href=\"news-standart-right-sidebar.html\">Right Sidebar</a></li>\r\n");
      out.write("												<li><a class=\"menu-item\"\r\n");
      out.write("													href=\"news-standart-left-sidebar.html\">Left Sidebar</a></li>\r\n");
      out.write("												<li><a class=\"menu-item\"\r\n");
      out.write("													href=\"news-standart-no-sidebar.html\">No Sidebar</a></li>\r\n");
      out.write("											</ul></li>\r\n");
      out.write("										<li><a class=\"menu-item\"\r\n");
      out.write("											href=\"news-grid-right-sidebar.html\">News Grid</a>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a class=\"menu-item\"\r\n");
      out.write("													href=\"news-grid-right-sidebar.html\">Right Sidebar</a></li>\r\n");
      out.write("												<li><a class=\"menu-item\"\r\n");
      out.write("													href=\"news-grid-left-sidebar.html\">Left Sidebar</a></li>\r\n");
      out.write("												<li><a class=\"menu-item\"\r\n");
      out.write("													href=\"news-grid-no-sidebar.html\">No Sidebar</a></li>\r\n");
      out.write("											</ul></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a class=\"menu-item\" href=\"#\">Elements</a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"preloader.html\">Preloader</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"icon-boxes.html\">Icon\r\n");
      out.write("												Boxes</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"badge.html\">Badge</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"counters.html\">Counters</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"gallery-popup.html\">Gallery\r\n");
      out.write("												Popup</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"icons-elegant.html\">Icons\r\n");
      out.write("												Elegant</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"icons-etline.html\">Icons\r\n");
      out.write("												Etline</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"icons-font-awesome.html\">Icons\r\n");
      out.write("												Font Awesome</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"map.html\">Map</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"modal.html\">Modal</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"popover.html\">Popover</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"tabs.html\">Tabs</a></li>\r\n");
      out.write("										<li><a class=\"menu-item\" href=\"tooltips.html\">Tooltips</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"de-flex-col\">\r\n");
      out.write("							<div class=\"menu_side_area\">\r\n");
      out.write("								<a href=\"customer-login.jsp\" class=\"btn-main\">Sign In</a> <span\r\n");
      out.write("									id=\"menu-btn\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	 <section id=\"subheader\" class=\"jarallax text-light\">\r\n");
      out.write("                <img src=\"images/background/2.jpg\" class=\"jarallax-img\" alt=\"\">\r\n");
      out.write("               \r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"js/plugins.js\"></script>\r\n");
      out.write("	<script src=\"js/designesia.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maps.googleapis.com/maps/api/js?key=insert_your_api_key_here&amp;libraries=places&amp;callback=initPlaces\"\r\n");
      out.write("		async=\"\" defer=\"\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<section aria-label=\"section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row g-custom-x\">\r\n");
      out.write("				<h3>Seller Create Account</h3>\r\n");
      out.write("				");

				String msg = (String) request.getAttribute("msg");
				
      out.write("\r\n");
      out.write("				");

				if (msg != null) {
				
      out.write("\r\n");
      out.write("				<h3 align=\"center\">\r\n");
      out.write("					");

					out.print(msg);
					
      out.write("\r\n");
      out.write("				</h3>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				");

				String msg1 = (String) request.getAttribute("msg1");
				if (msg1 != null) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<h4 class=\"contact-title\">\r\n");
      out.write("						");

						out.print(msg1);
						
      out.write("\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				<div class=\"de-box mb30  col-lg-8 mb-sm-30\">\r\n");
      out.write("					<form action=\"vendorController\" method=\"post\" class=\"form-border\"enctype=\"multipart/form-data\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-6 mb10\">\r\n");
      out.write("\r\n");
      out.write("								<div class=\"field-set\">\r\n");
      out.write("									<input type=\"text\" name=\"name\" class=\"form-control\"\r\n");
      out.write("										placeholder=\"Enter Name\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-6 mb10\">\r\n");
      out.write("								<div class=\"field-set\">\r\n");
      out.write("									<input type=\"text\" name=\"email\" class=\"form-control\"\r\n");
      out.write("										placeholder=\"Your email\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb10\">\r\n");
      out.write("								<div class=\"field-set\">\r\n");
      out.write("									<input type=\"password\" name=\"newp\" class=\"form-control\"\r\n");
      out.write("										placeholder=\" new password\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb10\">\r\n");
      out.write("								<div class=\"field-set\">\r\n");
      out.write("									<input type=\"password\" name=\"confirmnp\" class=\"form-control\"\r\n");
      out.write("										placeholder=\"confirm new password\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb10\">\r\n");
      out.write("								<div class=\"field-set\">\r\n");
      out.write("									<input type=\"text\" name=\"contact\" class=\"form-control\"\r\n");
      out.write("										placeholder=\"Enter contact\" required>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 mb10\">\r\n");
      out.write("								<div class=\"field-set\">\r\n");
      out.write("									<input class=\"form-control\" name=\"image\" id=\"subject\"\r\n");
      out.write("										type=\"file\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id='submit' class=\"mt20\">\r\n");
      out.write("							<input type='submit' value='register' name=\"action\"\r\n");
      out.write("								class=\"btn-main\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"title-line\"></div>\r\n");
      out.write("						<div class=\"row g-2\">\r\n");
      out.write("							<div class=\"col-lg-6 \">\r\n");
      out.write("								<h5>New Customer?</h5>\r\n");
      out.write("								<a href=\"customer-register.jsp\">Create Customer Account</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6 \">\r\n");
      out.write("								<h5>Already have customer account?</h5>\r\n");
      out.write("								<a href=\"customer-login.jsp\">Sign in</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<br>\r\n");
      out.write("						<div class=\"col-lg-6 \">\r\n");
      out.write("							<h5>Already have Business account?</h5>\r\n");
      out.write("							<a href=\"seller-login.jsp\">Sign in</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"de-box mb30 \">\r\n");
      out.write("						<a href=\"images/background/carr12.jpg\" class=\"image-popup\"> <span\r\n");
      out.write("							class=\"dih-title-wrap\"> <span class=\"dih-title\">Gallery\r\n");
      out.write("									Title</span>\r\n");
      out.write("						</span> <span class=\"dih-overlay\"></span> <img\r\n");
      out.write("							src=\"images/background/carr12.jpg\" class=\"lazy img-fluid\" alt=\"\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"de-box mb30\">\r\n");
      out.write("						<span> <img src=\"images/background/caw.jpg\"\r\n");
      out.write("							class=\"lazy img-fluid\" alt=\"\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"text-light\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row g-custom-x\">\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"widget\">\r\n");
      out.write("                            <h5>About Rentaly</h5>\r\n");
      out.write("                            <p>Where quality meets affordability. We understand the importance of a smooth and enjoyable journey without the burden of excessive costs. That's why we have meticulously crafted our offerings to provide you with top-notch vehicles at minimum expense.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"widget\">\r\n");
      out.write("                            <h5>Contact Info</h5>\r\n");
      out.write("                            <address class=\"s1\">\r\n");
      out.write("                                <span><i class=\"id-color fa fa-map-marker fa-lg\"></i>08 W 36th St, New York, NY 10001</span>\r\n");
      out.write("                                <span><i class=\"id-color fa fa-phone fa-lg\"></i>+1 333 9296</span>\r\n");
      out.write("                                <span><i class=\"id-color fa fa-envelope-o fa-lg\"></i><a href=\"mailto:contact@example.com\">contact@example.com</a></span>\r\n");
      out.write("                                <span><i class=\"id-color fa fa-file-pdf-o fa-lg\"></i><a href=\"#\">Download Brochure</a></span>\r\n");
      out.write("                            </address>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <h5>Quick Links</h5>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <div class=\"widget\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">About</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Careers</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">News</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Partners</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"widget\">\r\n");
      out.write("                            <h5>Social Network</h5>\r\n");
      out.write("                            <div class=\"social-icons\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook fa-lg\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter fa-lg\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-linkedin fa-lg\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-pinterest fa-lg\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-rss fa-lg\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"subfooter\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div class=\"de-flex\">\r\n");
      out.write("                                <div class=\"de-flex-col\">\r\n");
      out.write("                                    <a href=\"index.html\">\r\n");
      out.write("                                        Copyright 2023 - Rentaly by Designesia\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <ul class=\"menu-simple\">\r\n");
      out.write("                                    <li><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
