/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-16 06:01:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	min-height: 100%;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formContent {\r\n");
      out.write("	-webkit-border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	max-width: 450px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	-webkit-box-shadow: 0 30px 60px 0 rgba(0, 0, 0, 0.3);\r\n");
      out.write("	box-shadow: 0 30px 60px 0 rgba(0, 0, 0, 0.3);\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2.inactive {\r\n");
      out.write("	color: #cccccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2.active {\r\n");
      out.write("	color: #0d0d0d;\r\n");
      out.write("	border-bottom: 3px solid #5fbae9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=button], input[type=submit], input[type=reset] {\r\n");
      out.write("	background-color: #56baed;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 15px 80px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	-webkit-box-shadow: 0 10px 30px 0 rgba(95, 186, 233, 0.4);\r\n");
      out.write("	box-shadow: 0 10px 30px 0 rgba(95, 186, 233, 0.4);\r\n");
      out.write("	-webkit-border-radius: 5px 5px 5px 5px;\r\n");
      out.write("	border-radius: 5px 5px 5px 5px;\r\n");
      out.write("	margin: 5px 20px 20px 20px;\r\n");
      out.write("	-webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("	-moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("	-ms-transition: all 0.3s ease-in-out;\r\n");
      out.write("	-o-transition: all 0.3s ease-in-out;\r\n");
      out.write("	transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text] {\r\n");
      out.write("	background-color: #f6f6f6;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: #0d0d0d;\r\n");
      out.write("	padding: 15px 32px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	width: 85%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".colorr {\r\n");
      out.write("	background-color: #f6f6f6;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: #0d0d0d;\r\n");
      out.write("	padding: 15px 32px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	width: 85%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Register Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrapper \">\r\n");
      out.write("		<div id=\"formContent\">\r\n");
      out.write("			<form action=\"AdminController\" method=\"post\">\r\n");
      out.write("				<h2>Login Tops Technologies</h2>\r\n");
      out.write("\r\n");
      out.write("				");

				String msg = (String) request.getAttribute("msg");
				
      out.write("\r\n");
      out.write("				");

				if (msg != null) {
				
      out.write("\r\n");
      out.write("				<h3>\r\n");
      out.write("					");

					out.print(msg);
					
      out.write("\r\n");
      out.write("				</h3>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				");

				String msg1 = (String) request.getAttribute("msg1");
				
      out.write("\r\n");
      out.write("				");

				if (msg1 != null) {
				
      out.write("\r\n");
      out.write("				<h3>\r\n");
      out.write("					");

					out.print(msg1);
					
      out.write("\r\n");
      out.write("				</h3>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				<input class=\"colorr\" type=\"email\" id=\"login\" name=\"login\"\r\n");
      out.write("					placeholder=\"Email\"> <input class=\"colorr\" type=\"password\"\r\n");
      out.write("					id=\"password\" name=\"action\" placeholder=\"Password\"> <input\r\n");
      out.write("					type=\"submit\" name=\"action\" value=\"login\">\r\n");
      out.write("			</form>\r\n");
      out.write("			<div id=\"formFooter\">\r\n");
      out.write("				<a class=\"underlineHover\" href=\"#\">Forgot Password?</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"text-center\">\r\n");
      out.write("				<p>\r\n");
      out.write("					Not a member? <a href=\"Register.jsp\">Sign Up</a>\r\n");
      out.write("				</p>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
